// Mock data for the Store Discovery Platform

export type AvailabilityStatus = "in-stock" | "low-stock" | "out-of-stock" | "price-on-request";
export type VerificationStatus = "unverified" | "verified" | "partner";

export interface Store {
  id: string;
  name: string;
  category: string;
  categoryId: string;
  logo: string;
  banner: string;
  rating: number;
  reviewCount: number;
  verification: VerificationStatus;
  distance: string;
  eta: string;
  address: string;
  phone: string;
  hours: string;
  openNow: boolean;
  isSponsored: boolean;
  lastUpdated: string;
  description: string;
  productCategories: string[];
  products: Product[];
}

export interface Product {
  id: string;
  name: string;
  image: string;
  price: string;
  priceRange?: string;
  availability: AvailabilityStatus;
  stockCount?: number;
  category: string;
  description: string;
  storeId: string;
  storeName: string;
  lastUpdated: string;
  otherStoreCount?: number;
}

export interface StoreCategory {
  id: string;
  name: string;
  icon: string;
  storeCount: number;
}

export interface HeroBanner {
  id: string;
  image: string;
  title: string;
  subtitle: string;
  cta: string;
  isSponsored: boolean;
  sponsorName?: string;
  link?: string;
}

export const IMAGES = {
  pharmacy: "https://images.unsplash.com/photo-1604236929036-a783d8d07e9d?w=400&q=60",
  electronics: "https://images.unsplash.com/photo-1647766836665-098f3d7c653d?w=400&q=60",
  grocery: "https://images.unsplash.com/photo-1604236929036-a783d8d07e9d?w=400&q=60",
  phoneShop: "https://images.unsplash.com/photo-1692726502690-07ee61102964?w=400&q=60",
  spareParts: "https://images.unsplash.com/photo-1739488754789-5a2e85ee6a79?w=400&q=60",
  clothing: "https://images.unsplash.com/photo-1760287363707-851f4780b98c?w=400&q=60",
  beauty: "https://images.unsplash.com/photo-1624574966266-1cdd65b74500?w=400&q=60",
  medicine: "https://images.unsplash.com/photo-1631980839248-1a84a60c66ac?w=400&q=60",
  smartphone: "https://images.unsplash.com/photo-1627609834360-74948f361335?w=400&q=60",
  charger: "https://images.unsplash.com/photo-1731616103600-3fe7ccdc5a59?w=400&q=60",
  cookingOil: "https://images.unsplash.com/photo-1759332637000-50311b115c16?w=400&q=60",
  fashion: "https://images.unsplash.com/photo-1629737168267-a9cc18033938?w=400&q=60",
  rice: "https://images.unsplash.com/photo-1646980990815-1e97d5ee932f?w=400&q=60",
  brakePads: "https://images.unsplash.com/photo-1595444276957-9efea46598d7?w=400&q=60",
  earbuds: "https://images.unsplash.com/photo-1748698361079-fd70b999be1a?w=400&q=60",
  detergent: "https://images.unsplash.com/photo-1759846866217-e627e4478f82?w=400&q=60",
  heroBanner: "https://images.unsplash.com/photo-1760565030307-f05068b2585d?w=800&q=60",
};

export const heroBanners: HeroBanner[] = [
  {
    id: "hero-1",
    image: IMAGES.heroBanner,
    title: "Find what you need, near you",
    subtitle: "Discover stores with the items you're looking for",
    cta: "Start Searching",
    isSponsored: false,
  },
  {
    id: "hero-2",
    image: IMAGES.electronics,
    title: "New Electronics Stores Added",
    subtitle: "20+ verified electronics shops in Accra Central",
    cta: "Browse Electronics",
    isSponsored: true,
    sponsorName: "CompuGhana",
  },
  {
    id: "hero-3",
    image: IMAGES.pharmacy,
    title: "Pharmacy Finder",
    subtitle: "Check medicine availability before you travel",
    cta: "Find Pharmacy",
    isSponsored: false,
  },
];

export const storeCategories: StoreCategory[] = [
  { id: "cat-1", name: "Pharmacy", icon: "pill", storeCount: 45 },
  { id: "cat-2", name: "Electronics", icon: "smartphone", storeCount: 38 },
  { id: "cat-3", name: "Groceries", icon: "shopping-cart", storeCount: 62 },
  { id: "cat-4", name: "Fashion", icon: "shirt", storeCount: 51 },
  { id: "cat-5", name: "Spare Parts", icon: "wrench", storeCount: 29 },
  { id: "cat-6", name: "Beauty & Cosmetics", icon: "sparkles", storeCount: 34 },
  { id: "cat-7", name: "Phone Accessories", icon: "cable", storeCount: 42 },
  { id: "cat-8", name: "Home & Living", icon: "home", storeCount: 18 },
];

export const stores: Store[] = [
  {
    id: "store-1",
    name: "HealthPlus Pharmacy",
    category: "Pharmacy",
    categoryId: "cat-1",
    logo: IMAGES.pharmacy,
    banner: IMAGES.pharmacy,
    rating: 4.6,
    reviewCount: 128,
    verification: "verified",
    distance: "0.8 km",
    eta: "5 min",
    address: "23 Oxford Street, Osu, Accra",
    phone: "+233 24 567 8901",
    hours: "Mon-Sat: 7am - 9pm, Sun: 8am - 6pm",
    openNow: true,
    isSponsored: false,
    lastUpdated: "2h ago",
    description: "Your trusted neighbourhood pharmacy with a wide range of medicines, personal care items, and health supplements.",
    productCategories: ["Medicines", "Personal Care", "Vitamins", "First Aid"],
    products: [
      {
        id: "prod-1",
        name: "Paracetamol 500mg (Pack of 12)",
        image: IMAGES.medicine,
        price: "GHS 8.50",
        availability: "in-stock",
        stockCount: 150,
        category: "Medicines",
        description: "Effective pain relief and fever reducer. Each pack contains 12 tablets of 500mg paracetamol.",
        storeId: "store-1",
        storeName: "HealthPlus Pharmacy",
        lastUpdated: "2h ago",
        otherStoreCount: 5,
      },
      {
        id: "prod-2",
        name: "Vitamin C 1000mg",
        image: IMAGES.medicine,
        price: "GHS 35.00",
        availability: "in-stock",
        stockCount: 45,
        category: "Vitamins",
        description: "High-potency Vitamin C supplement to support immune health. 30 tablets per bottle.",
        storeId: "store-1",
        storeName: "HealthPlus Pharmacy",
        lastUpdated: "2h ago",
        otherStoreCount: 3,
      },
      {
        id: "prod-3",
        name: "Hand Sanitizer 250ml",
        image: IMAGES.medicine,
        price: "GHS 15.00",
        availability: "low-stock",
        stockCount: 8,
        category: "Personal Care",
        description: "Antibacterial hand sanitizer with 70% alcohol. Kills 99.9% of germs.",
        storeId: "store-1",
        storeName: "HealthPlus Pharmacy",
        lastUpdated: "2h ago",
      },
      {
        id: "prod-4",
        name: "First Aid Kit (Basic)",
        image: IMAGES.medicine,
        price: "GHS 65.00",
        availability: "in-stock",
        stockCount: 20,
        category: "First Aid",
        description: "Complete basic first aid kit with bandages, antiseptic, cotton, and scissors.",
        storeId: "store-1",
        storeName: "HealthPlus Pharmacy",
        lastUpdated: "2h ago",
      },
    ],
  },
  {
    id: "store-2",
    name: "CompuGhana Electronics",
    category: "Electronics",
    categoryId: "cat-2",
    logo: IMAGES.electronics,
    banner: IMAGES.electronics,
    rating: 4.3,
    reviewCount: 256,
    verification: "partner",
    distance: "1.2 km",
    eta: "8 min",
    address: "15 Ring Road, Accra Central",
    phone: "+233 30 222 3344",
    hours: "Mon-Sat: 9am - 7pm",
    openNow: true,
    isSponsored: true,
    lastUpdated: "1h ago",
    description: "Accra's leading electronics store. Authorized dealer for Samsung, Apple, HP, and more. Warranties available.",
    productCategories: ["Phones", "Laptops", "Accessories", "Audio"],
    products: [
      {
        id: "prod-5",
        name: "Samsung Galaxy A15",
        image: IMAGES.smartphone,
        price: "GHS 1,850",
        availability: "in-stock",
        stockCount: 12,
        category: "Phones",
        description: "6.5-inch display, 128GB storage, 4GB RAM. Dual SIM with expandable storage.",
        storeId: "store-2",
        storeName: "CompuGhana Electronics",
        lastUpdated: "1h ago",
        otherStoreCount: 4,
      },
      {
        id: "prod-6",
        name: "USB-C Fast Charger",
        image: IMAGES.charger,
        price: "GHS 45.00",
        availability: "in-stock",
        stockCount: 80,
        category: "Accessories",
        description: "25W USB-C fast charging adapter. Compatible with most modern smartphones.",
        storeId: "store-2",
        storeName: "CompuGhana Electronics",
        lastUpdated: "1h ago",
        otherStoreCount: 8,
      },
      {
        id: "prod-7",
        name: "Wireless Earbuds TWS",
        image: IMAGES.earbuds,
        price: "GHS 120.00",
        availability: "low-stock",
        stockCount: 5,
        category: "Audio",
        description: "True wireless stereo earbuds with 24h battery life, touch controls, and noise isolation.",
        storeId: "store-2",
        storeName: "CompuGhana Electronics",
        lastUpdated: "1h ago",
      },
      {
        id: "prod-8",
        name: "Laptop Stand Adjustable",
        image: IMAGES.electronics,
        price: "GHS 85.00",
        availability: "in-stock",
        stockCount: 25,
        category: "Accessories",
        description: "Ergonomic adjustable laptop stand. Fits laptops 10-17 inches.",
        storeId: "store-2",
        storeName: "CompuGhana Electronics",
        lastUpdated: "1h ago",
      },
    ],
  },
  {
    id: "store-3",
    name: "Melcom Supermarket",
    category: "Groceries",
    categoryId: "cat-3",
    logo: IMAGES.grocery,
    banner: IMAGES.grocery,
    rating: 4.1,
    reviewCount: 432,
    verification: "partner",
    distance: "2.5 km",
    eta: "12 min",
    address: "Kaneshie Market, Accra",
    phone: "+233 30 225 5566",
    hours: "Mon-Sun: 8am - 9pm",
    openNow: true,
    isSponsored: false,
    lastUpdated: "30 min ago",
    description: "Ghana's favourite supermarket chain. Groceries, household items, and everyday essentials at great prices.",
    productCategories: ["Food Staples", "Beverages", "Cleaning", "Personal Care"],
    products: [
      {
        id: "prod-9",
        name: "Royal Feast Rice 5kg",
        image: IMAGES.rice,
        price: "GHS 95.00",
        availability: "in-stock",
        stockCount: 200,
        category: "Food Staples",
        description: "Premium long grain rice. 5kg bag. Perfect for jollof, fried rice, and more.",
        storeId: "store-3",
        storeName: "Melcom Supermarket",
        lastUpdated: "30 min ago",
        otherStoreCount: 6,
      },
      {
        id: "prod-10",
        name: "Frytol Cooking Oil 5L",
        image: IMAGES.cookingOil,
        price: "GHS 120.00",
        availability: "in-stock",
        stockCount: 50,
        category: "Food Staples",
        description: "Pure refined vegetable cooking oil. 5-litre bottle.",
        storeId: "store-3",
        storeName: "Melcom Supermarket",
        lastUpdated: "30 min ago",
        otherStoreCount: 4,
      },
      {
        id: "prod-11",
        name: "Omo Detergent 2kg",
        image: IMAGES.detergent,
        price: "GHS 42.00",
        availability: "in-stock",
        stockCount: 75,
        category: "Cleaning",
        description: "Active Clean multi-purpose laundry detergent. 2kg pack.",
        storeId: "store-3",
        storeName: "Melcom Supermarket",
        lastUpdated: "30 min ago",
      },
    ],
  },
  {
    id: "store-4",
    name: "Kofi's Auto Parts",
    category: "Spare Parts",
    categoryId: "cat-5",
    logo: IMAGES.spareParts,
    banner: IMAGES.spareParts,
    rating: 4.4,
    reviewCount: 89,
    verification: "verified",
    distance: "3.1 km",
    eta: "15 min",
    address: "Abossey Okai Road, Accra",
    phone: "+233 24 111 2233",
    hours: "Mon-Sat: 7:30am - 6pm",
    openNow: true,
    isSponsored: false,
    lastUpdated: "4h ago",
    description: "Quality auto spare parts for Toyota, Honda, Hyundai, and more. Original and aftermarket parts available.",
    productCategories: ["Brake Parts", "Engine Parts", "Filters", "Electrical"],
    products: [
      {
        id: "prod-12",
        name: "Toyota Corolla Brake Pads (Front)",
        image: IMAGES.brakePads,
        price: "GHS 180.00",
        priceRange: "GHS 150 - 220",
        availability: "in-stock",
        stockCount: 15,
        category: "Brake Parts",
        description: "Front brake pad set for Toyota Corolla 2015-2023. Available in original and aftermarket options.",
        storeId: "store-4",
        storeName: "Kofi's Auto Parts",
        lastUpdated: "4h ago",
        otherStoreCount: 3,
      },
      {
        id: "prod-13",
        name: "Oil Filter (Universal)",
        image: IMAGES.spareParts,
        price: "GHS 25.00",
        availability: "in-stock",
        stockCount: 60,
        category: "Filters",
        description: "Universal oil filter. Compatible with most Toyota and Honda models.",
        storeId: "store-4",
        storeName: "Kofi's Auto Parts",
        lastUpdated: "4h ago",
      },
    ],
  },
  {
    id: "store-5",
    name: "Nana Ama Fashion",
    category: "Fashion",
    categoryId: "cat-4",
    logo: IMAGES.clothing,
    banner: IMAGES.fashion,
    rating: 4.7,
    reviewCount: 67,
    verification: "verified",
    distance: "1.8 km",
    eta: "10 min",
    address: "Makola Market, Accra",
    phone: "+233 24 333 4455",
    hours: "Mon-Sat: 8am - 6pm",
    openNow: false,
    isSponsored: false,
    lastUpdated: "1d ago",
    description: "Beautiful African prints and ready-to-wear fashion. Custom tailoring available in 3-5 days.",
    productCategories: ["Dresses", "Shirts", "Fabrics", "Jewellery and clothing accessories"],
    products: [
      {
        id: "prod-14",
        name: "Ankara Print Dress",
        image: IMAGES.fashion,
        price: "GHS 250.00",
        priceRange: "GHS 200 - 350",
        availability: "in-stock",
        stockCount: 8,
        category: "Dresses",
        description: "Beautiful Ankara print dress, hand-tailored. Available in multiple sizes and prints.",
        storeId: "store-5",
        storeName: "Nana Ama Fashion",
        lastUpdated: "1d ago",
        otherStoreCount: 2,
      },
    ],
  },
  {
    id: "store-6",
    name: "Accra Phone Hub",
    category: "Phone Accessories",
    categoryId: "cat-7",
    logo: IMAGES.phoneShop,
    banner: IMAGES.phoneShop,
    rating: 3.9,
    reviewCount: 156,
    verification: "unverified",
    distance: "0.5 km",
    eta: "3 min",
    address: "Circle Mall, Accra",
    phone: "+233 24 555 6677",
    hours: "Mon-Sun: 8am - 8pm",
    openNow: true,
    isSponsored: false,
    lastUpdated: "5h ago",
    description: "Phone cases, screen protectors, chargers, and accessories for all phone brands.",
    productCategories: ["Cases", "Chargers", "Screen Protectors", "Cables"],
    products: [
      {
        id: "prod-15",
        name: "iPhone 15 Case (Clear)",
        image: IMAGES.phoneShop,
        price: "GHS 30.00",
        availability: "in-stock",
        stockCount: 100,
        category: "Cases",
        description: "Clear protective case for iPhone 15. Shockproof with raised edges.",
        storeId: "store-6",
        storeName: "Accra Phone Hub",
        lastUpdated: "5h ago",
      },
      {
        id: "prod-16",
        name: "Lightning Cable 1m",
        image: IMAGES.charger,
        price: "GHS 20.00",
        availability: "in-stock",
        stockCount: 200,
        category: "Cables",
        description: "1-metre Lightning to USB cable. Fast charging compatible.",
        storeId: "store-6",
        storeName: "Accra Phone Hub",
        lastUpdated: "5h ago",
      },
    ],
  },
  {
    id: "store-7",
    name: "Glow Beauty Store",
    category: "Beauty & Cosmetics",
    categoryId: "cat-6",
    logo: IMAGES.beauty,
    banner: IMAGES.beauty,
    rating: 4.5,
    reviewCount: 92,
    verification: "verified",
    distance: "2.0 km",
    eta: "10 min",
    address: "East Legon, Accra",
    phone: "+233 24 777 8899",
    hours: "Mon-Sat: 9am - 7pm",
    openNow: true,
    isSponsored: true,
    lastUpdated: "3h ago",
    description: "Premium beauty and skincare products. Authorized stockist for major beauty brands.",
    productCategories: ["Skincare", "Makeup", "Hair Care", "Fragrance"],
    products: [
      {
        id: "prod-17",
        name: "Shea Butter Body Lotion 500ml",
        image: IMAGES.beauty,
        price: "GHS 55.00",
        availability: "in-stock",
        stockCount: 30,
        category: "Skincare",
        description: "Rich shea butter body lotion for deep moisturizing. Made with natural ingredients.",
        storeId: "store-7",
        storeName: "Glow Beauty Store",
        lastUpdated: "3h ago",
        otherStoreCount: 4,
      },
    ],
  },
  {
    id: "store-8",
    name: "PharmaCare Plus",
    category: "Pharmacy",
    categoryId: "cat-1",
    logo: IMAGES.pharmacy,
    banner: IMAGES.pharmacy,
    rating: 4.2,
    reviewCount: 78,
    verification: "verified",
    distance: "1.5 km",
    eta: "8 min",
    address: "Spintex Road, Accra",
    phone: "+233 24 888 9900",
    hours: "Mon-Sun: 7am - 10pm",
    openNow: true,
    isSponsored: false,
    lastUpdated: "1h ago",
    description: "24-hour pharmacy services. Wide range of medicines and health products.",
    productCategories: ["Medicines", "Baby Care", "Health Supplements"],
    products: [
      {
        id: "prod-18",
        name: "Paracetamol 500mg (Pack of 12)",
        image: IMAGES.medicine,
        price: "GHS 7.50",
        availability: "in-stock",
        stockCount: 200,
        category: "Medicines",
        description: "Effective pain relief and fever reducer. Each pack contains 12 tablets of 500mg paracetamol.",
        storeId: "store-8",
        storeName: "PharmaCare Plus",
        lastUpdated: "1h ago",
        otherStoreCount: 5,
      },
    ],
  },
  {
    id: "store-9",
    name: "TechWorld Ghana",
    category: "Electronics",
    categoryId: "cat-2",
    logo: IMAGES.electronics,
    banner: IMAGES.electronics,
    rating: 4.0,
    reviewCount: 189,
    verification: "verified",
    distance: "3.8 km",
    eta: "18 min",
    address: "Tema Community 1, Tema",
    phone: "+233 24 999 0011",
    hours: "Mon-Sat: 9am - 6pm",
    openNow: true,
    isSponsored: false,
    lastUpdated: "2h ago",
    description: "Affordable electronics and gadgets. Phone repairs also available.",
    productCategories: ["Phones", "Tablets", "Accessories", "Repairs"],
    products: [
      {
        id: "prod-19",
        name: "Samsung Galaxy A15",
        image: IMAGES.smartphone,
        price: "GHS 1,750",
        availability: "low-stock",
        stockCount: 3,
        category: "Phones",
        description: "6.5-inch display, 128GB storage, 4GB RAM. Dual SIM with expandable storage.",
        storeId: "store-9",
        storeName: "TechWorld Ghana",
        lastUpdated: "2h ago",
        otherStoreCount: 4,
      },
      {
        id: "prod-20",
        name: "USB-C Fast Charger",
        image: IMAGES.charger,
        price: "GHS 40.00",
        availability: "in-stock",
        stockCount: 50,
        category: "Accessories",
        description: "25W USB-C fast charging adapter. Compatible with most modern smartphones.",
        storeId: "store-9",
        storeName: "TechWorld Ghana",
        lastUpdated: "2h ago",
        otherStoreCount: 8,
      },
    ],
  },
];
